FROM postgres:17-alpine3.20
ENV POSTGRES_USER orthology_admin
ENV POSTGRES_PASSWORD orthology_admin
ENV POSTGRES_DB orthologydata
ENV PGDATA usr/local/data/postgresql/data/pgdata
COPY load /docker-entrypoint-initdb.d/
RUN mkdir -p /usr/local/data && chown -R postgres:postgres /usr/local/data
USER postgres