version: '3.7'
services:

  orthology-database:
    image: rwilsonebi/orthology-db:latest
    restart: always
    ports:
      - "6062:5432"
    networks:
      orthologydata:

  hasura:
    image: hasura/graphql-engine:v1.0.0-beta.2
    restart: always
    environment:
        - HASURA_GRAPHQL_DATABASE_URL=postgres://hasurauser:hasurauser@orthology-database:5432/orthologydata
        - HASURA_GRAPHQL_ENABLE_CONSOLE=true
        - HASURA_GRAPHQL_ENABLE_TELEMETRY=false
        - HASURA_GRAPHQL_UNAUTHORIZED_ROLE="public"
    ports:
      - "8086:8080"
    networks:
      orthologydata:
            
networks:
  orthologydata:

