apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
  namespace: mi-orthology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasura
    spec:
      imagePullSecrets:
      - name: hasuraregistrycredentials
      containers:
      #- image: hasura/graphql-engine:v1.2.2
      - image: dockerhub.ebi.ac.uk/mouse-informatics/hasura:v1.2.2
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://hasurauser:hasurauser@orthology-database:5432/orthologydata
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        - name: HASURA_GRAPHQL_ENABLE_TELEMETRY
          value: "false"
        - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
          value: "public"
        - name: HASURA_GRAPHQL_ENABLED_APIS
          value: "graphql,metadata"
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 60
        resources: {}
