apiVersion: v1
kind: Service
metadata:
  name: orthology-database-internal
  namespace: mi-orthology-dev
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: orthology-database
  type: NodePort
