apiVersion: v1
kind: ServiceAccount
metadata:
  name: orthology-admin
  namespace: orthology
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: orthology-full-access
  namespace: orthology
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: orthology-full-access-binding
  namespace: orthology
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orthology-full-access
subjects:
- kind: ServiceAccount
  name: orthology-admin
  namespace: orthology
